man_seed: 420911
batch_size: 16348
num_workers: 0
conv1:
  min_width: 2
  max_width: 256
  log_step: 2
conv2:
  min_width: 2
  max_width: 256
  log_step: 2
lr:
  min_val: 3e-5
  max_val: 3e-1
  log_step: 3
mom:
  min_val: 0.85
  max_val: 0.99
  step: 0.01
wd:
  min_val: 1e-6
  max_val: 1e-2
  log_step: 10


