DATASET: biobank
DATA_FOLDER: F:/HajduIstvan/UK_Biobank/
DATASET_PART: partitioned_dataset.npz
GAN_MODEL: AuxiliaryClassifierWGAN
RUN_NAME: biobank_acgan_1000_movmean_3
CLASS_FROZEN_INIT_FILENAME: frozen_init_bio_ch128_64_n32_16.pth
MATR_SIZE: 55
EXP_TRAIN_SIZES: (800,) #(100, 200, 500, 1000, 2000, 5000, 10000, None)
EXP_VAL_SIZES: (200,) #(100, 200, 500, 1000, 2000, 5000, 10000, None)
BATCH_SIZE:
  CLASS:
    TRAIN: 64
    VAL: 64
    TEST: 64
  GAN:
    TRAIN: 64
    GENERATE: 64
NUM_WORKERS:
  CLASS: 0
  GAN: 0
ITER_MAX:
  CLASS: 30001 # 30001
  GAN: 1001 # 1001
ITER_VAL:
  CLASS: 1000
  GAN: 200
ITER_SAVE:
#  CLASS: 5000
  GAN: 25
ITER_TB:
  CLASS: 10
  GAN: 1 # 1
OPTIMIZER:
  CLASS:
    ALG: adam
    LR_ADAM: 1e-3
    BETAS: (0.9, 0.9)
    WD: 1e-4
    POWER: 0.8 # 0.8
  GAN:
    G:
      ALG: adam
      LR_ADAM: 2e-5
      WD_ADAM: 1e-4
#      LR_SGD: 1e-4
#      LR_RMS: 1e-4
#      MOMENTUM: 0.2
      POWER: 1
      BETAS: (0.5, 0.9)
    D:
      ALG: adam
      LR_ADAM: 5e-5
      WD_ADAM: 1e-4
      POWER: 0.9 #1
      #      LR_SGD: 1e-4
#      LR_RMS: 1e-4
#      MOMENTUM: 0.2
      BETAS: (0.7,0.9) #(0.5, 0.9)
ARCHITECTURE:
  CLASS:
    COORDCONV: (0,0)
    CHS: (128, 64) #
    NEURONS: (32, 16, 1)
    DROPOUT: 0.5
    LOSS_FN: L1
  GAN:
    NOISE_DIMS: 32
    DIM: 128
    CRITIC_ITERS: 10 # 3
    CRITIC_ITER_DECAY: 1
    COORDCONV_G: (1, 1)
    COORDCONV_D: (1, 1)
    DROPOUT: 0.5
    LAMBDA_CRITIC: 1
    LAMBDA_REGR: 1
    LAMBDA_GP: 0 #10 #5
    LAMBDA_CT: 0 # Use 0 if no CT wanted
    CT_M: 0
    LRELU_SLOPE: 0.01
    LOSS_NORM_MOVING_MEAN: 10
#SPLIT_LIMITS: (0.7, 0.9)
AGE_INTERVAL: (44.583333333333336, 80.66666666666667)
#OUTLY_MIXER: 0.5
#OUTLY_THRESHOLD: 0.0025
GEN_IMG_NUM: 9000  #80000
GEN_IMG_MULT: 9
#GEN_EARLY_IT: 385