DATASET: age_small
RELATIVE_DATA_FOLDER: libs/datasets/age/
DATASET_PART: age_part.npz

SUPERVISE_TYPE: regress
CLASS_FROZEN_INIT_FILENAME: frozen_init.pth
MATR_SIZE: 111
BATCH_SIZE:
  CLASS:
    TRAIN: 128
    VAL: 64
    TEST: 128
  GAN:
    TRAIN: 64
    GENERATE: 100
NUM_WORKERS:
  CLASS: 0
  GAN: 0
ITER_MAX:
  CLASS: 30001
  GAN: 3001
ITER_VAL:
  CLASS: 100
  GAN: 50
ITER_SAVE:
#  CLASS: 5000
  GAN: 50
ITER_TB:
  CLASS: 10
  GAN: 1
OPTIMIZER:
  CLASS:
    ALG: adam
    LR_ADAM: 1e-4
    BETAS: (0.9, 0.9)
  GAN:
    G:
      ALG: adam
      LR_ADAM: 1e-4
#      LR_SGD: 1e-4
#      LR_RMS: 1e-4
#      MOMENTUM: 0.2
      BETAS: (0.5, 0.9)
    D:
      ALG: adam
      LR_ADAM: 1e-4
#      LR_SGD: 1e-4
#      LR_RMS: 1e-4
#      MOMENTUM: 0.2
      BETAS: (0.5, 0.9)
ARCHITECTURE:
  CLASS:
    CHS: (32, 64)
    NEURONS: (32, 16, 1)
    DROPOUT: 0.5
    LOSS_FN: L1
  GAN:
    NOISE_DIMS: 111
    DIM: 48
    CRITIC_ITERS: 3
    DROPOUT: 0.5
    LAMBDA_REGR: 10
    LAMBDA_GP: 10
    LAMBDA_CT: 0 # Use 0 if no CT wanted
    CT_M: 0
#SPLIT_LIMITS: (0.7, 0.9)
AGE_INTERVAL: (19, 89)
#OUTLY_MIXER: 0.5
#OUTLY_THRESHOLD: 0.0025
GEN_IMG_NUM: 16000
#GEN_EARLY_IT: 385