DATASET: age
RELATIVE_DATA_FOLDER: libs/datasets/age/
#DATASET_WHOLE: autism_dataset_whole.npz
DATASET_PART: age_part.npz
SPLIT:
  TRAIN: train
  VAL: val
  TEST: test
SUPERVISE_TYPE: binary
MATR_SIZE: 111
BATCH_SIZE:
  CLASS:
    TRAIN: 32
    VAL: 64
    TEST: 32
  GAN:
    TRAIN: 64
    VAL: 32
    TEST: 32
    GENERATE: 50
NUM_WORKERS:
  CLASS: 0
  GAN: 0
ITER_MAX:
  CLASS: 10001
  GAN: 1001
ITER_VAL: 100
ITER_SAVE:
  CLASS: 250
  GAN: 50
ITER_TB:
  CLASS: 10
  GAN: 1
LOG_DIR:
  CLASS:
    PURE: runs/classifier/age/binary/pure
    MIXED: runs/classifier/age/binary/mixed
  GAN: runs/gan/age/binary
SAVE_DIR:
  CLASS:
    PURE: save/classifier/age/binary/pure
    MIXED: save/classifier/age/binary/mixed
  GAN: save/gan/age/binary
OPTIMIZER:
  CLASS:
    ALG: adam
    LR: 1e-4
    BETAS: (0.9, 0.999)
  GAN:
    G:
      ALG: adam
      LR: 1e-4
      BETAS: (0.5, 0.9)
    D:
      ALG: adam
      LR: 1e-4
      BETAS: (0.5, 0.9)
ARCHITECTURE:
  CLASS:
    CHS: (64, 128)
    NEURONS: (64, 32, 2)
    DROPOUT: 0.5
    DROPOUT_LAYERS: (1, 1, 1, 1)
    BN_LAYERS: (1, 1, 1, 1)
  GAN:
    LAMBDA: 10
    NOISE_DIMS: 111
    DIM: 48
    CRITIC_ITERS: 3
    DROPOUT: 0.5
SPLIT_LIMITS: (0.7, 0.9)
OUTLY_MIXER: 0.5
OUTLY_THRESHOLD: 0.0025
GEN_IMG_NUM: 5000
GEN_EARLY_IT: 300
